[build]
  command = "npm run build:content && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.11.1"
  NODE_OPTIONS = "--no-deprecation"
  NEXT_DISABLE_ESLINT = "true"
  NEXT_DISABLE_TYPECHECK = "true"

