[build]
  command = "yarn build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NEXT_DISABLE_ESLINT = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
  skip = true
