[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.18.2"
  NODE_OPTIONS = "--no-deprecation"
  NEXT_DISABLE_ESLINT = "true"
  NEXT_DISABLE_TYPECHECK = "true"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

